// Curated gift card brands available for redemption
// Logos use a unified neon styling — brand names render as gradient text in cards.
export interface GiftCardBrand {
  id: string;
  name: string;
  category: string;
  minInr: number;
  maxInr: number;
  emoji: string;
  color: string; // tailwind gradient classes
  popular?: boolean;
}

export const GIFT_CARD_CATEGORIES = [
  "All",
  "Shopping",
  "Food",
  "Entertainment",
  "Travel",
  "Gaming",
  "Fashion",
  "Beauty",
  "Grocery",
  "Telecom",
] as const;

const make = (
  id: string,
  name: string,
  category: string,
  emoji: string,
  color: string,
  popular = false,
  minInr = 100,
  maxInr = 5000
): GiftCardBrand => ({ id, name, category, emoji, color, popular, minInr, maxInr });

export const GIFT_CARDS: GiftCardBrand[] = [
  // Shopping
  make("amazon", "Amazon", "Shopping", "🛒", "from-amber-500 to-orange-600", true),
  make("flipkart", "Flipkart", "Shopping", "🛍️", "from-blue-500 to-indigo-600", true),
  make("myntra", "Myntra", "Fashion", "👗", "from-pink-500 to-rose-600", true),
  make("ajio", "Ajio", "Fashion", "🧥", "from-fuchsia-500 to-purple-600"),
  make("meesho", "Meesho", "Shopping", "🎀", "from-pink-400 to-fuchsia-500"),
  make("nykaa", "Nykaa", "Beauty", "💄", "from-rose-400 to-pink-600", true),
  make("nykaa-fashion", "Nykaa Fashion", "Fashion", "👜", "from-pink-500 to-purple-600"),
  make("tata-cliq", "Tata CLiQ", "Shopping", "🛒", "from-red-500 to-rose-600"),
  make("tata-cliq-luxury", "Tata CLiQ Luxury", "Fashion", "💎", "from-yellow-500 to-amber-600"),
  make("croma", "Croma", "Shopping", "📺", "from-emerald-500 to-teal-600"),
  make("reliance-digital", "Reliance Digital", "Shopping", "🔌", "from-blue-600 to-cyan-600"),
  make("vijay-sales", "Vijay Sales", "Shopping", "📱", "from-orange-500 to-red-600"),
  make("snapdeal", "Snapdeal", "Shopping", "📦", "from-red-500 to-orange-500"),
  make("shopclues", "ShopClues", "Shopping", "🎁", "from-orange-400 to-pink-500"),
  make("lifestyle", "Lifestyle", "Fashion", "👚", "from-purple-500 to-pink-600"),
  make("max", "Max Fashion", "Fashion", "👕", "from-blue-500 to-cyan-500"),
  make("westside", "Westside", "Fashion", "🧣", "from-amber-600 to-orange-700"),
  make("pantaloons", "Pantaloons", "Fashion", "👖", "from-yellow-500 to-orange-500"),
  make("shoppers-stop", "Shoppers Stop", "Fashion", "🛍️", "from-rose-500 to-red-600"),
  make("fbb", "FBB", "Fashion", "👔", "from-blue-500 to-purple-500"),
  make("biba", "Biba", "Fashion", "👘", "from-pink-500 to-rose-600"),
  make("global-desi", "Global Desi", "Fashion", "🥻", "from-orange-500 to-pink-500"),
  make("w", "W for Woman", "Fashion", "💃", "from-fuchsia-500 to-pink-600"),
  make("fabindia", "FabIndia", "Fashion", "🪡", "from-amber-500 to-orange-600"),
  make("levi", "Levi's", "Fashion", "👖", "from-red-600 to-orange-600"),
  make("us-polo", "US Polo Assn.", "Fashion", "🏇", "from-blue-600 to-indigo-700"),
  make("allen-solly", "Allen Solly", "Fashion", "👔", "from-emerald-500 to-teal-600"),
  make("van-heusen", "Van Heusen", "Fashion", "🤵", "from-slate-500 to-blue-600"),
  make("peter-england", "Peter England", "Fashion", "👞", "from-blue-500 to-slate-600"),
  make("louis-philippe", "Louis Philippe", "Fashion", "🎩", "from-yellow-600 to-amber-700"),
  make("park-avenue", "Park Avenue", "Fashion", "🧥", "from-stone-500 to-zinc-600"),
  make("raymond", "Raymond", "Fashion", "🧵", "from-amber-600 to-yellow-700"),
  make("manyavar", "Manyavar", "Fashion", "🪯", "from-amber-500 to-red-600"),
  make("titan", "Titan Watches", "Fashion", "⌚", "from-slate-500 to-gray-700"),
  make("fastrack", "Fastrack", "Fashion", "🕶️", "from-orange-500 to-red-600"),
  make("tanishq", "Tanishq", "Fashion", "💍", "from-yellow-500 to-amber-600"),
  make("caratlane", "CaratLane", "Fashion", "💎", "from-rose-400 to-pink-500"),
  make("bluestone", "BlueStone", "Fashion", "💠", "from-cyan-500 to-blue-600"),
  make("kalyan", "Kalyan Jewellers", "Fashion", "👑", "from-yellow-500 to-orange-600"),
  make("malabar-gold", "Malabar Gold", "Fashion", "🪙", "from-amber-500 to-yellow-600"),
  make("pc-jeweller", "PC Jeweller", "Fashion", "💍", "from-pink-500 to-rose-600"),

  // Food & Restaurants
  make("swiggy", "Swiggy", "Food", "🛵", "from-orange-500 to-red-500", true),
  make("zomato", "Zomato", "Food", "🍕", "from-red-500 to-pink-600", true),
  make("dominos", "Domino's", "Food", "🍕", "from-blue-600 to-red-600"),
  make("pizza-hut", "Pizza Hut", "Food", "🍕", "from-red-600 to-orange-600"),
  make("kfc", "KFC", "Food", "🍗", "from-red-700 to-rose-700"),
  make("mcdonalds", "McDonald's", "Food", "🍔", "from-yellow-500 to-red-600"),
  make("burger-king", "Burger King", "Food", "🍔", "from-orange-600 to-red-700"),
  make("subway", "Subway", "Food", "🥪", "from-green-500 to-yellow-500"),
  make("starbucks", "Starbucks", "Food", "☕", "from-emerald-700 to-green-800"),
  make("ccd", "Cafe Coffee Day", "Food", "☕", "from-amber-700 to-red-700"),
  make("barista", "Barista", "Food", "☕", "from-amber-800 to-stone-700"),
  make("dunkin", "Dunkin'", "Food", "🍩", "from-pink-500 to-orange-500"),
  make("baskin-robbins", "Baskin Robbins", "Food", "🍦", "from-pink-400 to-blue-500"),
  make("haldirams", "Haldiram's", "Food", "🍛", "from-orange-500 to-red-600"),
  make("bikanervala", "Bikanervala", "Food", "🍛", "from-red-500 to-orange-600"),
  make("behrouz", "Behrouz Biryani", "Food", "🍚", "from-amber-600 to-red-700"),
  make("faasos", "Faasos", "Food", "🌯", "from-red-500 to-orange-500"),
  make("box8", "Box8", "Food", "🍱", "from-orange-500 to-yellow-500"),
  make("oven-story", "Oven Story", "Food", "🍕", "from-red-500 to-pink-600"),
  make("fresh-menu", "FreshMenu", "Food", "🥗", "from-green-500 to-lime-500"),
  make("eatfit", "EatFit", "Food", "🥑", "from-lime-500 to-green-600"),
  make("dineout", "Dineout", "Food", "🍽️", "from-rose-500 to-pink-600"),
  make("eazy-diner", "EazyDiner", "Food", "🍷", "from-purple-500 to-pink-600"),

  // Grocery
  make("bigbasket", "BigBasket", "Grocery", "🥬", "from-emerald-600 to-green-700", true),
  make("blinkit", "Blinkit", "Grocery", "⚡", "from-yellow-500 to-amber-600"),
  make("zepto", "Zepto", "Grocery", "🛒", "from-violet-500 to-purple-600"),
  make("instamart", "Swiggy Instamart", "Grocery", "🥛", "from-orange-500 to-amber-500"),
  make("dunzo", "Dunzo", "Grocery", "🛵", "from-pink-500 to-rose-600"),
  make("grofers", "Grofers", "Grocery", "🥕", "from-emerald-500 to-teal-600"),
  make("dmart", "DMart", "Grocery", "🛒", "from-green-600 to-emerald-700"),
  make("nature-basket", "Nature's Basket", "Grocery", "🥦", "from-lime-500 to-emerald-600"),
  make("spencers", "Spencer's", "Grocery", "🍎", "from-red-500 to-rose-600"),
  make("more", "More Retail", "Grocery", "🛒", "from-cyan-500 to-blue-600"),

  // Entertainment & OTT
  make("bookmyshow", "BookMyShow", "Entertainment", "🎬", "from-red-500 to-rose-600", true),
  make("pvr", "PVR Cinemas", "Entertainment", "🎟️", "from-amber-500 to-orange-600"),
  make("inox", "INOX", "Entertainment", "🎥", "from-blue-500 to-cyan-600"),
  make("netflix", "Netflix", "Entertainment", "📺", "from-red-600 to-rose-700", true),
  make("prime-video", "Prime Video", "Entertainment", "🎞️", "from-blue-500 to-cyan-500"),
  make("hotstar", "Disney+ Hotstar", "Entertainment", "🌟", "from-blue-700 to-indigo-800"),
  make("zee5", "Zee5", "Entertainment", "📡", "from-purple-500 to-pink-600"),
  make("sonyliv", "SonyLIV", "Entertainment", "📺", "from-orange-500 to-red-600"),
  make("jio-cinema", "JioCinema", "Entertainment", "🎬", "from-blue-600 to-indigo-700"),
  make("alt-balaji", "ALTBalaji", "Entertainment", "🎭", "from-pink-500 to-rose-600"),
  make("voot", "Voot", "Entertainment", "📺", "from-fuchsia-500 to-purple-600"),
  make("erosnow", "Eros Now", "Entertainment", "🎬", "from-rose-500 to-red-600"),
  make("spotify", "Spotify", "Entertainment", "🎵", "from-emerald-500 to-green-600"),
  make("gaana", "Gaana", "Entertainment", "🎶", "from-red-500 to-orange-500"),
  make("wynk", "Wynk Music", "Entertainment", "🎧", "from-pink-500 to-purple-600"),
  make("jio-saavn", "JioSaavn", "Entertainment", "🎼", "from-emerald-500 to-teal-600"),
  make("youtube-premium", "YouTube Premium", "Entertainment", "▶️", "from-red-600 to-rose-700"),
  make("apple-music", "Apple Music", "Entertainment", "🎵", "from-pink-500 to-rose-500"),

  // Gaming
  make("google-play", "Google Play", "Gaming", "▶️", "from-blue-500 to-green-500", true),
  make("app-store", "App Store", "Gaming", "🍎", "from-blue-500 to-cyan-500"),
  make("xbox", "Xbox", "Gaming", "🎮", "from-emerald-600 to-green-700"),
  make("playstation", "PlayStation", "Gaming", "🎮", "from-blue-700 to-indigo-800"),
  make("steam", "Steam", "Gaming", "🕹️", "from-slate-700 to-blue-800"),
  make("nintendo", "Nintendo eShop", "Gaming", "🎮", "from-red-600 to-rose-700"),
  make("free-fire", "Free Fire", "Gaming", "🔥", "from-orange-500 to-red-600"),
  make("pubg", "BGMI", "Gaming", "🔫", "from-yellow-500 to-orange-600"),
  make("ml-bangbang", "Mobile Legends", "Gaming", "⚔️", "from-blue-600 to-violet-700"),
  make("clash-royale", "Clash Royale", "Gaming", "👑", "from-yellow-500 to-amber-600"),
  make("fortnite", "Fortnite V-Bucks", "Gaming", "🛡️", "from-purple-600 to-fuchsia-700"),
  make("roblox", "Roblox", "Gaming", "🧱", "from-red-500 to-rose-600"),
  make("epic", "Epic Games", "Gaming", "🎮", "from-slate-700 to-zinc-800"),
  make("razer", "Razer Gold", "Gaming", "💚", "from-emerald-500 to-green-700"),

  // Travel
  make("makemytrip", "MakeMyTrip", "Travel", "✈️", "from-red-500 to-orange-500"),
  make("goibibo", "Goibibo", "Travel", "🧳", "from-orange-500 to-amber-500"),
  make("yatra", "Yatra", "Travel", "🗺️", "from-blue-500 to-indigo-600"),
  make("cleartrip", "Cleartrip", "Travel", "✈️", "from-cyan-500 to-blue-600"),
  make("ixigo", "Ixigo", "Travel", "🛫", "from-orange-500 to-pink-500"),
  make("easemytrip", "EaseMyTrip", "Travel", "🌍", "from-cyan-400 to-teal-500"),
  make("oyo", "OYO", "Travel", "🏨", "from-red-500 to-rose-600"),
  make("treebo", "Treebo", "Travel", "🌳", "from-emerald-500 to-green-600"),
  make("fab-hotels", "FabHotels", "Travel", "🛏️", "from-violet-500 to-purple-600"),
  make("airbnb", "Airbnb", "Travel", "🏡", "from-pink-500 to-rose-600"),
  make("uber", "Uber", "Travel", "🚗", "from-slate-700 to-zinc-800"),
  make("ola", "Ola", "Travel", "🚕", "from-yellow-500 to-orange-500"),
  make("rapido", "Rapido", "Travel", "🛵", "from-yellow-400 to-amber-500"),
  make("indigo", "IndiGo", "Travel", "✈️", "from-indigo-600 to-blue-700"),
  make("vistara", "Vistara", "Travel", "✈️", "from-violet-700 to-purple-800"),
  make("air-india", "Air India", "Travel", "🛩️", "from-red-500 to-rose-600"),
  make("spicejet", "SpiceJet", "Travel", "✈️", "from-red-500 to-orange-500"),
  make("redbus", "redBus", "Travel", "🚌", "from-red-500 to-rose-600"),
  make("abhibus", "AbhiBus", "Travel", "🚍", "from-orange-500 to-red-500"),
  make("irctc", "IRCTC", "Travel", "🚆", "from-blue-600 to-cyan-600"),

  // Telecom & Utilities
  make("jio", "Jio Recharge", "Telecom", "📶", "from-blue-600 to-indigo-700"),
  make("airtel", "Airtel Recharge", "Telecom", "📱", "from-red-600 to-rose-700"),
  make("vi", "Vi (Vodafone Idea)", "Telecom", "📡", "from-red-500 to-pink-600"),
  make("bsnl", "BSNL Recharge", "Telecom", "☎️", "from-blue-500 to-cyan-500"),
  make("mtnl", "MTNL", "Telecom", "📞", "from-emerald-500 to-teal-600"),

  // Beauty & Wellness
  make("mamaearth", "Mamaearth", "Beauty", "🌿", "from-emerald-500 to-lime-600"),
  make("plum", "Plum Goodness", "Beauty", "🌸", "from-pink-400 to-rose-500"),
  make("the-body-shop", "The Body Shop", "Beauty", "🌺", "from-emerald-600 to-green-700"),
  make("forest-essentials", "Forest Essentials", "Beauty", "🌱", "from-lime-600 to-emerald-700"),
  make("sephora", "Sephora", "Beauty", "💋", "from-stone-700 to-zinc-800"),
  make("mac", "MAC", "Beauty", "💄", "from-rose-600 to-pink-700"),
  make("urban-company", "Urban Company", "Beauty", "🧴", "from-pink-500 to-rose-600"),
  make("cult-fit", "cult.fit", "Beauty", "🏋️", "from-orange-500 to-red-600"),
  make("healthkart", "HealthKart", "Beauty", "💊", "from-emerald-500 to-teal-600"),
  make("1mg", "Tata 1mg", "Beauty", "💊", "from-orange-500 to-red-500"),
  make("apollo-pharmacy", "Apollo Pharmacy", "Beauty", "🏥", "from-red-500 to-rose-600"),
  make("netmeds", "Netmeds", "Beauty", "💊", "from-emerald-600 to-green-700"),
  make("pharmeasy", "PharmEasy", "Beauty", "🩺", "from-cyan-500 to-blue-600"),
  make("practo", "Practo", "Beauty", "👨‍⚕️", "from-cyan-500 to-teal-600"),

  // Misc Premium
  make("decathlon", "Decathlon", "Shopping", "⚽", "from-blue-700 to-cyan-700"),
  make("ikea", "IKEA", "Shopping", "🛋️", "from-blue-600 to-yellow-500"),
  make("urban-ladder", "Urban Ladder", "Shopping", "🪑", "from-amber-600 to-orange-700"),
  make("pepperfry", "Pepperfry", "Shopping", "🛏️", "from-orange-500 to-red-600"),
  make("hometown", "HomeTown", "Shopping", "🏠", "from-purple-500 to-pink-600"),
  make("first-cry", "FirstCry", "Shopping", "🍼", "from-pink-500 to-rose-600"),
  make("hopscotch", "Hopscotch", "Shopping", "🧸", "from-fuchsia-500 to-pink-600"),
  make("mama-mia", "Mama Mia", "Shopping", "🤰", "from-pink-400 to-rose-500"),
  make("decathlon-india", "Decathlon India", "Shopping", "🚴", "from-blue-700 to-cyan-700"),
  make("ace-turtle", "Ace Turtle", "Shopping", "🐢", "from-emerald-500 to-teal-600"),
  make("nike", "Nike", "Fashion", "👟", "from-stone-700 to-zinc-800"),
  make("adidas", "Adidas", "Fashion", "👟", "from-slate-700 to-blue-800"),
  make("puma", "Puma", "Fashion", "🐆", "from-amber-500 to-orange-600"),
  make("reebok", "Reebok", "Fashion", "👟", "from-blue-600 to-cyan-600"),
  make("skechers", "Skechers", "Fashion", "👟", "from-blue-500 to-cyan-500"),
  make("crocs", "Crocs", "Fashion", "🩴", "from-emerald-500 to-lime-600"),
  make("woodland", "Woodland", "Fashion", "🥾", "from-amber-700 to-orange-800"),
  make("bata", "Bata", "Fashion", "👞", "from-red-600 to-rose-700"),
  make("liberty", "Liberty Shoes", "Fashion", "👞", "from-stone-600 to-zinc-700"),
  make("metro", "Metro Shoes", "Fashion", "👠", "from-amber-600 to-yellow-700"),
  make("clarks", "Clarks", "Fashion", "👞", "from-amber-700 to-stone-700"),
  make("h-and-m", "H&M", "Fashion", "👕", "from-red-600 to-rose-700"),
  make("zara", "Zara", "Fashion", "👗", "from-stone-700 to-zinc-800"),
  make("uniqlo", "Uniqlo", "Fashion", "👚", "from-red-500 to-rose-600"),
  make("forever21", "Forever 21", "Fashion", "👕", "from-yellow-500 to-amber-600"),
  make("only", "ONLY", "Fashion", "👗", "from-rose-500 to-pink-600"),
  make("vero-moda", "Vero Moda", "Fashion", "👚", "from-fuchsia-500 to-pink-600"),
  make("jack-jones", "Jack & Jones", "Fashion", "👔", "from-stone-700 to-zinc-800"),
  make("the-souled-store", "The Souled Store", "Fashion", "👕", "from-violet-500 to-fuchsia-600"),
  make("bewakoof", "Bewakoof", "Fashion", "🧢", "from-yellow-500 to-orange-600"),
  make("urbanic", "Urbanic", "Fashion", "👗", "from-pink-500 to-fuchsia-600"),
];

// Quick lookups
export const findGiftCard = (id: string) => GIFT_CARDS.find((g) => g.id === id);
export const giftCardsByCategory = (cat: string) =>
  cat === "All" ? GIFT_CARDS : GIFT_CARDS.filter((g) => g.category === cat);
